In [2]:
import numpy as np

# Vector is a mathematical object that has both magnitude and direction
# It is represented as an ordered list of numbers
# For example, a 2D vector can be represented as [x, y]
# A 3D vector can be represented as [x, y, z]

# Creating a vector
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Adding two vectors
'''
    Explanation:

    Two vectors are:
    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Addition formula:
    v1 + v2 = (a1 + b1, a2 + b2, a3 + b3)

    Here,
    (1 + 4, 2 + 5, 3 + 6) = (5, 7, 9)
'''
# (1 + 4, 2 + 5, 3 + 6) = (5, 7, 9)
v3 = v1 + v2
print(f"Addition v3: {v3}") 
# output: Addition v3: [5 7 9]

# Subtracting two vectors
'''
    Explanation:

    Two vectors are:
    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Subtraction formula:
    v1 - v2 = (a1 - b1, a2 - b2, a3 - b3)

    Here,
    (1 - 4, 2 - 5, 3 - 6) = (-3, -3, -3)
'''
# (1 - 4, 2 - 5, 3 - 6) = (-3, -3, -3)
v4 = v1 - v2
print(f"Subtraction v4: {v4}")
# output: Subtraction v4: [-3 -3 -3]

# Multiplying a vector by a scalar
'''
    Explanation:

    v1 = [1, 2, 3]
    scalar = 2

    Multiplication formula:
    v1 * scalar = (a1 * scalar, a2 * scalar, a3 * scalar)

    Here,
    (1 * 2, 2 * 2, 3 * 2) = (2, 4, 6)
'''
# (1 * 2, 2 * 2, 3 * 2) = (2, 4, 6)
v5 = v1 * 2
print(f"Multiplication v5: {v5}")
# output: Multiplication v5: [2 4 6]

# Dividing a vector by a scalar
'''
    Explanation:

    v1 = [1, 2, 3]
    scalar = 2

    Division formula:
    v1 / scalar = (a1 / scalar, a2 / scalar, a3 / scalar)

    Here,
    (1 / 2, 2 / 2, 3 / 2) = (0.5, 1, 1.5)
'''
# (1 / 2, 2 / 2, 3 / 2) = (0.5, 1, 1.5)
v6 = v1 / 2
print(f"Division v6: {v6}")
# output: Division v6: [0.5 1.  1.5]

# Dot product of two vectors
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Dot Product formula:
    v1 · v2 = (a1 * b1) + (a2 * b2) + (a3 * b3)

    Here,
    (1 * 4) + (2 * 5) + (3 * 6)
    = 4 + 10 + 18
    = 32
'''
# (1 * 4) + (2 * 5) + (3 * 6) = 32
v7 = np.dot(v1, v2)
print(f"Dot product v7: {v7}")
# output: Dot product v7: 32

# Cross product of two vectors
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Cross Product formula:
    v1 * v2 = (a2 * b3 - a3 * b2,
            a3 * b1 - a1 * b3,
            a1 * b2 - a2 * b1)

    Here,

    (2 * 6 - 3 * 5,
    3 * 4 - 1 * 6,
    1 * 5 - 2 * 4)

    = (12 - 15,
    12 - 6,
    5 - 8)

    = (-3, 6, -3)
'''
# (2 * 6 - 3 * 5, 3 * 4 - 1 * 6, 1 * 5 - 2 * 4) = (-3, 6, -3)
v8 = np.cross(v1, v2)
print(f"Cross product v8: {v8}")
# output: Cross product v8: [-3  6 -3]

# Magnitude of a vector
'''
    Explanation:

    v1 = [1, 2, 3]

    Magnitude (Length) formula:

    ||v1|| = √(a1² + a2² + a3²)

    Here,

    √(1² + 2² + 3²)
    = √(1 + 4 + 9)
    = √14
    = 3.7416573867739413
'''
# sqrt(1^2 + 2^2 + 3^2) = 3.7416573867739413
v9 = np.linalg.norm(v1)
print(f"Magnitude v9: {v9}")

# Angle between two vectors
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Angle formula:

    θ = arccos((v1 · v2) / (||v1|| * ||v2||))

    Here,

    v1 · v2 = (1 * 4) + (2 * 5) + (3 * 6)
            = 4 + 10 + 18
            = 32

    ||v1|| = √(1² + 2² + 3²)
        = √14

    ||v2|| = √(4² + 5² + 6²)
        = √77

    Therefore,

    θ = arccos(32 / (√14 * √77))
    = 0.2257261285527342 radians

    ≈ 12.93°
'''
# arccos((1 * 4 + 2 * 5 + 3 * 6) / (sqrt(1^2 + 2^2 + 3^2) * sqrt(4^2 + 5^2 + 6^2))) = 0.9746318461970762
v10 = np.arccos(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))
print(f"Angle v10: {v10}")
# output: Angle v10: 0.2257261285527342

# Projection of v1 onto v2
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Projection formula:
    proj_v2(v1) = ((v1 · v2) / (v2 · v2)) * v2

    Here,
    ((1 * 4 + 2 * 5 + 3 * 6) / (4^2 + 5^2 + 6^2)) * (4, 5, 6)
    = (32 / 77) * (4, 5, 6)
    = (1.6, 2, 2.4)
'''
# ((1 * 4 + 2 * 5 + 3 * 6) / (4^2 + 5^2 + 6^2)) * (4, 5, 6) = (1.6, 2, 2.4)
v11 = np.dot(v1, v2) / np.dot(v2, v2) * v2
print(f"Projection v11: {v11}")
# output: Projection v11: [1.66233766 2.07792208 2.49350649]

# Reflection of v1 onto v2
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Reflection formula:

    ref_v2(v1) = v1 - 2 × ((v1 · v2) / (v2 · v2)) × v2

    Here,

    v1 · v2 = (1 × 4) + (2 × 5) + (3 × 6)
            = 4 + 10 + 18
            = 32

    v2 · v2 = (4² + 5² + 6²)
            = 16 + 25 + 36
            = 77

    So,

    ref_v2(v1)
    = v1 - 2 × (32/77) × (4, 5, 6)

    First compute:
    2 × (32/77) = 64/77

    So,
    ref_v2(v1)
    = (1, 2, 3) - (64/77) × (4, 5, 6)

    = (1, 2, 3) - (256/77, 320/77, 384/77)

    Now convert v1 to /77 form:

    (1, 2, 3) = (77/77, 154/77, 231/77)

    Subtract:

    = ((77 - 256)/77, (154 - 320)/77, (231 - 384)/77)

    = (-179/77, -166/77, -153/77)

    ≈ (-2.32467532, -2.15584416, -1.98701299)
'''
# v1 - 2 * ((1 * 4 + 2 * 5 + 3 * 6) / (4^2 + 5^2 + 6^2)) * (4, 5, 6) = (-0.6, -0, 0.6)
v12 = v1 - 2 * np.dot(v1, v2) / np.dot(v2, v2) * v2
print(f"Reflection v12: {v12}")
# output: Reflection v12: [-2.32467532 -2.15584416 -1.98701299]

# Orthogonal projection of v1 onto v2
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Orthogonal projection formula:

    orth_proj_v2(v1) = ((v1 · v2) / (v2 · v2)) × v2

    Here,

    v1 · v2 = (1 × 4) + (2 × 5) + (3 × 6)
            = 4 + 10 + 18
            = 32

    v2 · v2 = (4² + 5² + 6²)
            = 16 + 25 + 36
            = 77

    So,

    orth_proj_v2(v1)
    = (32 / 77) × (4, 5, 6)

    Now compute each component:

    = ( (32×4)/77, (32×5)/77, (32×6)/77 )
    = (128/77, 160/77, 192/77)

    ≈ (1.6623, 2.0779, 2.4935)
'''
# ((1 * 4 + 2 * 5 + 3 * 6) / (4^2 + 5^2 + 6^2)) * (4, 5, 6) = (1.6, 2, 2.4)
v13 = np.dot(v1, v2) / np.dot(v2, v2) * v2
print(f"Orthogonal projection v13: {v13}")
# output: Orthogonal projection v13: [1.66233766 2.07792208 2.49350649]

# Orthogonal reflection of v1 onto v2
'''
    Explanation:

    Two vectors are:

    v1 = [1, 2, 3]
    v2 = [4, 5, 6]

    Orthogonal reflection formula:

    orth_ref_v2(v1) = 2 × orth_proj_v2(v1) − v1

    First compute projection:

    orth_proj_v2(v1) = ((v1 · v2) / (v2 · v2)) × v2

    v1 · v2 = (1×4) + (2×5) + (3×6)
            = 4 + 10 + 18
            = 32

    v2 · v2 = 4² + 5² + 6²
            = 16 + 25 + 36
            = 77

    So,

    orth_proj_v2(v1) = (32/77) × (4, 5, 6)
                    = (128/77, 160/77, 192/77)
                    ≈ (1.6623, 2.0779, 2.4935)

    Now reflection:

    orth_ref_v2(v1)
    = 2 × (128/77, 160/77, 192/77) − (1, 2, 3)

    = (256/77, 320/77, 384/77) − (1, 2, 3)

    Convert v1 to /77:

    (1, 2, 3) = (77/77, 154/77, 231/77)

    Subtract:

    = ((256−77)/77, (320−154)/77, (384−231)/77)

    = (179/77, 166/77, 153/77)

    ≈ (2.3247, 2.1558, 1.9870)
'''
# 2 * ((1 * 4 + 2 * 5 + 3 * 6) / (4^2 + 5^2 + 6^2)) * (4, 5, 6) - (1, 2, 3) = (2.3247, 2.1558, 1.9870)
v14 = 2 * np.dot(v1, v2) / np.dot(v2, v2) * v2 - v1
print(f"Orthogonal reflection v14: {v14}")
# output: Orthogonal reflection v14: [2.32467532 2.15584416 1.98701299]

# Determinant of a 2x2 matrix
'''
    Explanation:

    Matrix A:
    [[1, 2],
    [3, 4]]

    Determinant formula:
    det(A) = ad - bc

    Here,
    a = 1, b = 2, c = 3, d = 4

    So,
    det(A) = (1 * 4) - (2 * 3)
    = 4 - 6
    = -2
'''
v15 = np.linalg.det([[1, 2], [3, 4]])
print(f"Determinant v15: {v15}")
# output: Determinant v15: -2.0



Addition v3: [5 7 9]
Subtraction v4: [-3 -3 -3]
Multiplication v5: [2 4 6]
Division v6: [0.5 1.  1.5]
Dot product v7: 32
Cross product v8: [-3  6 -3]
Magnitude v9: 3.7416573867739413
Angle v10: 0.2257261285527342
Projection v11: [1.66233766 2.07792208 2.49350649]
Reflection v12: [-2.32467532 -2.15584416 -1.98701299]
Orthogonal projection v13: [1.66233766 2.07792208 2.49350649]
Orthogonal reflection v14: [2.32467532 2.15584416 1.98701299]
Determinant v15: -2.0000000000000004


In [ ]:
import numpy as np

# Field Addition
'''
    Field:
    A field is a mathematical structure in which addition, subtraction,
    multiplication, and division (except division by zero) are defined
    and satisfy the following properties:

    Properties:
    1. Commutative
    2. Associative
    3. Distributive
    4. Additive Identity
    5. Additive Inverse

    Example:

    Matrix A:
    [[1, 2],
    [3, 4]]

    Matrix B:
    [[5, 6],
    [7, 8]]

    Matrix Addition Formula:
    A + B = [[a11 + b11, a12 + b12],
            [a21 + b21, a22 + b22]]

    Calculation:
    A + B = [[1 + 5, 2 + 6],
            [3 + 7, 4 + 8]]

    Result:
    [[6, 8],
    [10, 12]]
'''

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

v16 = np.add(A, B)

print("Field addition v16:")
print(v16)


Field addition v16:
[[ 6  8]
 [10 12]]


In [ ]:
import numpy as np
'''
    Commutative Property:
    Two elements a and b are said to be commutative if a + b = b + a

    Commutative Law: A + B = B + A
    Example:

    Matrix A:
    [[1, 2],
    [3, 4]]

    Matrix B:
    [[1, 2],
    [3, 4]]

    Matrix Addition Formula:
    A + B = [[a11 + b11, a12 + b12],
            [a21 + b21, a22 + b22]]

    Calculation:
    A + B = [[1 + 1, 2 + 2],
            [3 + 3, 4 + 4]]

    Result:
    [[2, 4],
    [6, 8]]

    B + A = [[1 + 1, 2 + 2],
            [3 + 3, 4 + 4]]

    Result:
    [[2, 4],
    [6, 8]]

    A + B = B + A
'''

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[1, 2],
              [3, 4]])

v17 = np.add(A, B)
v18 = np.add(B, A)

print("Commutative v17:")
print(v17)
print("Commutative v18:")
print(v18)

Commutative v17:
[[2 4]
 [6 8]]
Commutative v18:
[[2 4]
 [6 8]]


In [1]:
import numpy as np
'''
    Associative Property
    The Associative Property states that matrices can be grouped in any order during addition.

    Associative Law:
    (A + B) + C = A + (B + C)

    Example:

    Matrix A:
    [[1, 2],
    [3, 4]]

    Matrix B:
    [[1, 2],
    [3, 4]]

    Matrix C:
    [[1, 2],
    [3, 4]]

    Step 1: A + B
    [[1+1, 2+2],
    [3+3, 4+4]]
    =
    [[2, 4],
    [6, 8]]

    Step 2: (A + B) + C
    [[2+1, 4+2],
    [6+3, 8+4]]
    =
    [[3, 6],
    [9, 12]]

    Step 3: B + C
    [[1+1, 2+2],
    [3+3, 4+4]]
    =
    [[2, 4],
    [6, 8]]

    Step 4: A + (B + C)
    [[1+2, 2+4],
    [3+6, 4+8]]
    =
    [[3, 6],
    [9, 12]]

    Therefore,

    (A + B) + C = A + (B + C)

    Final Answer:
    [[3, 6],
    [9, 12]]
    
'''

A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
C = np.array([[1, 2], [3, 4]])

print((A + B) + C)
print(A + (B + C))


[[ 3  6]
 [ 9 12]]
[[ 3  6]
 [ 9 12]]


In [ ]:
'''
    Distributive Property

    The Distributive Property states that matrix multiplication is distributive over matrix addition.

    Distributive Law:
    A × (B + C) = (A × B) + (A × C)

    Example:

    Matrix A:
    [[1, 2],
    [3, 4]]

    Matrix B:
    [[1, 0],
    [0, 1]]

    Matrix C:
    [[2, 1],
    [1, 2]]

    Step 1: B + C
    [[1+2, 0+1],
    [0+1, 1+2]]
    =
    [[3, 1],
    [1, 3]]

    Step 2: A × (B + C)
    [[1, 2],
    [3, 4]]
    ×
    [[3, 1],
    [1, 3]]
    =
    [[5, 7],
    [13, 15]]

    Step 3: A × B
    [[1, 2],
    [3, 4]]
    ×
    [[1, 0],
    [0, 1]]
    =
    [[1, 2],
    [3, 4]]

    Step 4: A × C
    [[1, 2],
    [3, 4]]
    ×
    [[2, 1],
    [1, 2]]
    =
    [[4, 5],
    [10, 11]]

    Step 5: (A × B) + (A × C)
    [[1+4, 2+5],
    [3+10, 4+11]]
    =
    [[5, 7],
    [13, 15]]

    Therefore,

    A × (B + C) = (A × B) + (A × C)

    Final Answer:
    [[5, 7],
    [13, 15]]
'''
import numpy as np

# Define matrices A, B, and C
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[1, 0],
              [0, 1]])

C = np.array([[2, 1],
              [1, 2]])

# Step 1: Calculate B + C
B_plus_C = B + C
print("B + C:")
print(B_plus_C)

# Step 2: Calculate A × (B + C)
A_times_B_plus_C = A @ B_plus_C
print("\nA × (B + C):")
print(A_times_B_plus_C)

# Step 3: Calculate A × B
A_times_B = A @ B
print("\nA × B:")
print(A_times_B)

# Step 4: Calculate A × C
A_times_C = A @ C
print("\nA × C:")
print(A_times_C)

# Step 5: Calculate (A × B) + (A × C)
A_times_B_plus_A_times_C = A_times_B + A_times_C
print("\n(A × B) + (A × C):")
print(A_times_B_plus_A_times_C)

# Verify the distributive property
print("\nVerification:")
print("A × (B + C) == (A × B) + (A × C):")
print(np.array_equal(A_times_B_plus_C, A_times_B_plus_A_times_C))


'\n    Distributive Property\n\n    The Distributive Property states that matrix multiplication is distributive over matrix addition.\n\n    Distributive Law:\n    A × (B + C) = (A × B) + (A × C)\n\n    Example:\n\n    Matrix A:\n    [[1, 2],\n    [3, 4]]\n\n    Matrix B:\n    [[1, 0],\n    [0, 1]]\n\n    Matrix C:\n    [[2, 1],\n    [1, 2]]\n\n    Step 1: B + C\n    [[1+2, 0+1],\n    [0+1, 1+2]]\n    =\n    [[3, 1],\n    [1, 3]]\n\n    Step 2: A × (B + C)\n    [[1, 2],\n    [3, 4]]\n    ×\n    [[3, 1],\n    [1, 3]]\n    =\n    [[5, 7],\n    [13, 15]]\n\n    Step 3: A × B\n    [[1, 2],\n    [3, 4]]\n    ×\n    [[1, 0],\n    [0, 1]]\n    =\n    [[1, 2],\n    [3, 4]]\n\n    Step 4: A × C\n    [[1, 2],\n    [3, 4]]\n    ×\n    [[2, 1],\n    [1, 2]]\n    =\n    [[4, 5],\n    [10, 11]]\n\n    Step 5: (A × B) + (A × C)\n    [[1+4, 2+5],\n    [3+10, 4+11]]\n    =\n    [[5, 7],\n    [13, 15]]\n\n    Therefore,\n\n    A × (B + C) = (A × B) + (A × C)\n\n    Final Answer:\n    [[5, 7],\n    [13, 

In [ ]:
'''
    Additive Identity

    Definition:
    The additive identity is a number which, when added to any number, gives the number itself.

    Additive Identity = 0 (Zero)

    Formula:
    A + 0 = A
    0 + A = A

    Examples:
    5 + 0 = 5
    12 + 0 = 12
    -8 + 0 = -8
    0 + 25 = 25

    Key Point:
    The additive identity is 0 because adding 0 to any number does not change its value.

    Memory Tip:
    Adding Zero Changes Nothing.
'''

A = 5
print(A + 0)
print(0 + A)

5
5


In [ ]:
'''
    # Additive Inverse

    **Definition:**
    The additive inverse of a number is the number that, when added to the original number, gives zero.

    **Formula:**
    **Additive Inverse of x = -x**

    **Examples:**

    * The additive inverse of **5** is **-5**, because **5 + (-5) = 0**.
    * The additive inverse of **-8** is **8**, because **-8 + 8 = 0**.
    * The additive inverse of **0** is **0**, because **0 + 0 = 0**.

    **Key Point:**
    The additive inverse changes the sign of a number:

    * Positive → Negative
    * Negative → Positive
    * Zero → Zero

'''

def additive_inverse(x):
    return -x

print(additive_inverse(5))
print(additive_inverse(-3))
print(additive_inverse(0))


-5
3
0
